In [4]:
import pickle    
import pandas as pd
test = pickle.load(open('/Users/zhongshannan/Desktop/train.pickle', 'rb'))

for i in range(len(test['text'])):
    test['text'][i] = test['text'][i][:-1]
    #test['image'][i] = test['image'][i][0][:-4]  # 取到jpg
    test['image'][i] = test['image'][i][:] # 全取
    test['label'][i] = "fake" if test['label'][i] == 0 else "real" # label从01转换fake real
    test['event'][i] = test['event'][i]

test1 = pd.DataFrame(columns = ['text'] , data=test['text'])
test2 = pd.DataFrame(columns = ['image'] , data=test['image'])
test3 = pd.DataFrame(columns = ['label'] , data=test['label'])
test4 = pd.DataFrame(columns = ['event_label'] , data=test['event'])
df = pd.concat([test1,test2,test3,test4], axis=1)
df.to_csv("/Users/zhongshannan/Documents/fakenews_detection/dataset/twitter_recon/twitter_cleaned/weibo_train.csv", encoding='utf-8', index=False)

# twitter mvae处理

In [9]:
import pickle
import pandas as pd
test = pickle.load(open('/Users/zhongshannan/Documents/fakenews_detection/dataset/twitter_recon/twitter_mvae/train.pickle', 'rb'))
sum(test['label'])

5188

In [8]:
import pickle
import pandas as pd
test = pickle.load(open('/Users/zhongshannan/Documents/fakenews_detection/dataset/twitter_recon/twitter_mvae/test.pickle', 'rb'))

for i in range(len(test['text'])):
    test['text'][i] = test['text'][i][:-1]
    #test['image'][i] = test['image'][i][0][:-4]  # 取到jpg
    test['image'][i] = test['image'][i][0][:] + '.jpg' # 全取
    test['label'][i] = "fake" if test['label'][i] == 0 else "real" # label从01转换fake real
    test['event'][i] = test['event'][i]

test1 = pd.DataFrame(columns = ['text'] , data=test['text'])
test2 = pd.DataFrame(columns = ['image'] , data=test['image'])
test3 = pd.DataFrame(columns = ['label'] , data=test['label'])
test4 = pd.DataFrame(columns = ['event_label'] , data=test['event'])
df = pd.concat([test1,test2,test3,test4], axis=1)
df.to_csv("/Users/zhongshannan/Documents/fakenews_detection/dataset/twitter_recon/twitter_mvae/weibo_test.csv", encoding='utf-8', index=False)

检查验证集事件

In [2]:
import pandas as pd
file1 = pd.read_csv('/Users/zhongshannan/Documents/fakenews_detection/dataset/twitter_recon/twitter_mvae/train.csv')

# images=[]
# for image_name in file['image']:
#     images.append(image_name[:-7]) 
# set(images),print(file['event_label'].unique())

len(set(file1['event_label']))

9

In [3]:
file1.head()

Unnamed: 0             post_id        image_id  \
0           0  324597532548276224  boston_fake_03   
1           1  325145334739267584  boston_fake_23   
2           2  325152091423248385  boston_fake_34   
3           3  324315545572896768  boston_fake_15   
4           4  324581777614180352  boston_fake_08   

                                       original_post post_text  label  \
0  do not need feds to solve the  #bostonbombing ...        []      1   
1  pic  comparison of  #boston suspect sunil trip...        []      1   
2  i am not completely convinced that it is  this...        []      1   
3  4chan and the bombing  just throwing it out there        []      1   
4     4chan thinks they found pictures of the bomber        []      1   

   event_label  
0            0  
1            0  
2            0  
3            0  
4            0

In [2]:
import pandas as pd
file_ = pd.read_csv('/Users/zhongshannan/Downloads/train.csv')
file_['event_label'].value_counts()

3    7589
0     482
4     266
1     191
8      86
5      70
2      43
6       3
7       2
Name: event_label, dtype: int64

处理新Twitter数据

In [15]:
import pandas as pd
import numpy as np
file_ = pd.read_csv('/Users/zhongshannan/Downloads/validate.csv')
# 转为numpy
file_ = np.array(file_)
file_[0,:]

array([0, 578844275061981184, 'eclipse_01',
       'dit dus  0  rt   \\@news_executive  the solar eclipse seen from international space station   #solareclipse  #iss  #space',
       '[]', 1, 0], dtype=object)

In [16]:
# 加.jpg
for i in range(len(file_)):
    file_[i, 2] = file_[i, 2] + '.jpg'
file_[0,:]

array([0, 578844275061981184, 'eclipse_01.jpg',
       'dit dus  0  rt   \\@news_executive  the solar eclipse seen from international space station   #solareclipse  #iss  #space',
       '[]', 1, 0], dtype=object)

In [17]:
# 转换标签
for i in range(len(file_)):
    if file_[i, 5] == 0:
        file_[i, 5] = 'real'
    else:
        file_[i, 5] = 'fake'
file_[0,:]

array([0, 578844275061981184, 'eclipse_01.jpg',
       'dit dus  0  rt   \\@news_executive  the solar eclipse seen from international space station   #solareclipse  #iss  #space',
       '[]', 'fake', 0], dtype=object)

In [18]:
# 取出所需列
file_ = file_[:,[2,3,5,6]]
file_[0,:]

array(['eclipse_01.jpg',
       'dit dus  0  rt   \\@news_executive  the solar eclipse seen from international space station   #solareclipse  #iss  #space',
       'fake', 0], dtype=object)

In [19]:
file_ = pd.DataFrame(file_, columns=['image','text','label','event_label'])

In [20]:
file_.to_csv('twitter_validation.csv',encoding='utf-8',index=False)

检查

In [2]:
import pandas as pd
file_ = pd.read_csv('/Users/zhongshannan/Documents/fakenews_detection/dataset/twitter_recon/twitter_mvae/twitter_train.csv')
file_['event_label'].value_counts(),file_['label'].value_counts()

(3    7589
 0     482
 4     266
 1     191
 8      86
 5      70
 2      43
 6       3
 7       2
 Name: event_label, dtype: int64,
 fake    4774
 real    3958
 Name: label, dtype: int64)